baseURL = "https://jingyi-cui.github.io"
title = "Jingyi Cui"
theme = "etch"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Welcome"
  copyright = "Copyright © 2024 Jingyi Cui"
  dark = "auto"
  highlight = true

[menu]

  [[menu.main]]
    identifier = "aboutme"
    name = "aboutme"
    title = "aboutme"
    url = "/aboutme/"
    weight = 20

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allows HTML in Markdown
  unsafe = true

